"""transaction_datetime

Revision ID: a13e55ad238a
Revises: 755c697f85a3
Create Date: 2025-11-16 11:57:49.661304

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a13e55ad238a"
down_revision: Union[str, None] = "755c697f85a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns as nullable first
    op.add_column(
        "credits", sa.Column("transaction_date", sa.DateTime(), nullable=True)
    )
    op.add_column("debits", sa.Column("transaction_date", sa.DateTime(), nullable=True))

    # Copy data from created_at to transaction_date
    op.execute(
        """
        UPDATE credits
        SET transaction_date = created_at
        WHERE transaction_date IS NULL;
        """
    )

    op.execute(
        """
        UPDATE debits
        SET transaction_date = created_at
        WHERE transaction_date IS NULL;
        """
    )

    # Now make the columns non-nullable
    op.alter_column("credits", "transaction_date", nullable=False)
    op.alter_column("debits", "transaction_date", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("debits", "transaction_date")
    op.drop_column("credits", "transaction_date")
    # ### end Alembic commands ###
