"""transactions

Revision ID: 59864df39271
Revises: 901a8d0e9c9a
Create Date: 2025-11-07 15:07:34.946638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59864df39271'
down_revision: Union[str, None] = '901a8d0e9c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='BYN', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['internal_users.id'], name=op.f('fk_credits_user_id_internal_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credits'))
    )
    op.create_table('debits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='BYN', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['internal_users.id'], name=op.f('fk_debits_user_id_internal_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debits'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debits')
    op.drop_table('credits')
    # ### end Alembic commands ###
