"""base_users

Revision ID: 901a8d0e9c9a
Revises:
Create Date: 2025-11-07 13:56:32.591608

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "901a8d0e9c9a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "internal_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("external_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_internal_users")),
        sa.UniqueConstraint("external_id", name=op.f("uq_internal_users_external_id")),
    )
    op.create_index(
        op.f("ix_internal_users_name"), "internal_users", ["name"], unique=False
    )
    op.create_table(
        "users_whitelist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_whitelist")),
        sa.UniqueConstraint("username", name=op.f("uq_users_whitelist_username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_whitelist")
    op.drop_index(op.f("ix_internal_users_name"), table_name="internal_users")
    op.drop_table("internal_users")
    # ### end Alembic commands ###
