"""transaction_categories

Revision ID: 755c697f85a3
Revises: 59864df39271
Create Date: 2025-11-12 07:41:54.030259

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "755c697f85a3"
down_revision: Union[str, None] = "59864df39271"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_categories")),
    )
    op.add_column("credits", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_credits_category_id_transaction_categories"),
        "credits",
        "transaction_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("debits", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_debits_category_id_transaction_categories"),
        "debits",
        "transaction_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_debits_category_id_transaction_categories"),
        "debits",
        type_="foreignkey",
    )
    op.drop_column("debits", "category_id")
    op.drop_constraint(
        op.f("fk_credits_category_id_transaction_categories"),
        "credits",
        type_="foreignkey",
    )
    op.drop_column("credits", "category_id")
    op.drop_table("transaction_categories")
    # ### end Alembic commands ###
