"""user_default_currency

Revision ID: ddbf5b614819
Revises: a13e55ad238a
Create Date: 2026-08-28 18:35:56.769012

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddbf5b614819"
down_revision: Union[str, None] = "a13e55ad238a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "internal_users",
        sa.Column(
            "default_currency",
            sa.String(length=3),
            server_default="BYN",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("internal_users", "default_currency")
    # ### end Alembic commands ###
